spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 10000
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://root:root@localhost}
      database: ${MONGODB_DATABASE:chatDb}

app:
  auth:
    jwks-url: https://dev-3nr5zs54v5d1iflv.us.auth0.com/.well-known/jwks.json

logging:
  level:
    org:
      apache:
        http: DEBUG