package com.cursochat.websocket.providers;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Map;

@SpringBootTest
public class JsonWebTokenProviderTest {

    @Autowired
    private TokenProvider tokenProvider;

    @Test
    void test(){
        Map<String, String> decoded = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5VRWFfTXBWbDBNQ1VSVE0yR0tnaSJ9.eyJnaXZlbl9uYW1lIjoiVGhpYWdvIiwiZmFtaWx5X25hbWUiOiJCYXJyZXRvIiwibmlja25hbWUiOiJ0aGlhZ29icnJ0ODgiLCJuYW1lIjoiVGhpYWdvIEJhcnJldG8iLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUVkRlRwNEJiQWFLSmpPdjg2QlloNkxvRUxFSjJHNHZmcFFvSU8wYkJGcGVqQT1zOTYtYyIsImxvY2FsZSI6ImVuIiwidXBkYXRlZF9hdCI6IjIwMjItMTItMjhUMjE6NDQ6NTAuODc0WiIsImVtYWlsIjoidGhpYWdvYnJydDg4QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2Rldi0zbnI1enM1NHY1ZDFpZmx2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNjg4ODE5Njk1MzM2MjAxMTI3MCIsImF1ZCI6Imc5QjFLaEl6OXhlRTRTOURLaEVOWmZTWjB4OVlpN1FtIiwiaWF0IjoxNjcyMjYzODkyLCJleHAiOjE2NzIyOTk4OTIsInNpZCI6Ilh4U3dIY1Z3TUtQeklNMjF5dVVnUnIwTjhkeTZueFVWIiwibm9uY2UiOiJPRmN1Tmt0SGN6ZG9TWHBGYkZsNlNsbEJSMlozZEM1a2NGcEpRMjlFZVc4d1pWTlNUR05XVTNGaVRRPT0ifQ.IGMdTA8VSw-dfOhqcMArGOt5uqYz8kQHeidIipnmP4XUiAy4S7XhuLjbimqVYddpdrjUwofOvU0MiIB9uiazLeBpTlrhUsqgz1fyUgWNkSZ_nQHfbSHdDIZKnTS_cQFB2w5kzMlgGPkX7Myz4Nq6KoWxK2tGS8ukKWkHEurn8uSJV9McXFRNs--pG25YL76pgV3lqcVmJk71yPfEWdP_lCxAfxWlJNFs-ijMjP_-ykvy_SK3bUfJLrg33HnogX6DMG4SWZ5UMNRi2cVthrrUitmx4-GmOaxDsJDVmkIEUME3Qn7CSg5OVn-PsnnQHDCXjO8OeHOHKnSLZtF14DoWjg");
        System.out.println(decoded);
    }

}
